---
namespace: stevefulme1
name: weka
version: 2.0.0
readme: README.md
authors:
  - Steve Fulmer <sfulmer@redhat.com>
description: Ansible collection for WekaIO storage management
license_file: LICENSE
tags:
  - storage
  - weka
  - wekaio
  - filesystem
  - nfs
  - s3
dependencies: {}
repository: https://github.com/stevefulme1/ansible-weka
documentation: https://github.com/stevefulme1/ansible-weka/blob/main/README.md
homepage: https://github.com/stevefulme1/ansible-weka
issues: https://github.com/stevefulme1/ansible-weka/issues
build_ignore:
  - .github
  - .gitignore
  - tests/output
  - '*.tar.gz'
requires_ansible: '>=2.16.0'
