---
# defaults/main.yml for weka_capacity_expansion

# Target host
weka_capacity_expansion_host: ""

# Authentication
weka_capacity_expansion_username: ""
weka_capacity_expansion_password: ""
weka_capacity_expansion_api_key: ""

# Behavior
weka_capacity_expansion_validate_certs: true
weka_capacity_expansion_state: present
