---
argument_specs:
  main:
    short_description: "Set up alerting and event monitoring"
    options:
      weka_monitoring_host:
        description: Target host address
        type: str
        required: true
      weka_monitoring_username:
        description: Authentication username
        type: str
      weka_monitoring_password:
        description: Authentication password
        type: str
      weka_monitoring_api_key:
        description: API key for authentication
        type: str
      weka_monitoring_validate_certs:
        description: Validate SSL certificates
        type: bool
        default: true
      weka_monitoring_state:
        description: Desired state
        type: str
        default: present
        choices: [present, absent]
